env:
  browser: true
  es2020: true
  node: true
extends:
  - "eslint:recommended"
  - "prettier"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "emotion"
ignorePatterns:
  - "**/__tests__/*"
rules:
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/no-var-requires": off