env:
  browser: true
  es2020: true
  node: true
extends:
  - "eslint:recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
ignorePatterns:
  - "**/__tests__/*"
rules: {}
